# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-23 16:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='type',
            new_name='proj_type',
        ),
    ]
