# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-23 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0003_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='funds',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
