# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-21 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_reg_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.CharField(default='USER', max_length=255),
            preserve_default=False,
        ),
    ]
