# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-24 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_reg_app', '0002_user_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='prof_pic',
            field=models.FileField(default='images/default-icon.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='user',
            name='url',
            field=models.TextField(default='https://static.thenounproject.com/png/629576-200.png'),
        ),
    ]
